apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-dns
spec: 
  replicas: 1
  selector:
    matchLabels:
      name: nginx-dns 
  serviceName: "nginx"
  template:
    metadata:
      labels:
        name: nginx-dns
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dns
spec:
  selector:
    name: nginx-dns
  clusterIP: None
  ports:
  - port: 8080
